[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

# Include future-dated posts on PR deploy previews only.
[context.deploy-preview]
  command = "bundle exec jekyll build --future"
