name: Build and Jekyll site and run htmlproofer

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Fetch main
        run: |
          git fetch origin main --depth 1
          git branch

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 #v2.8.0
        with:
          fail: true
          args: --no-progress --root-dir _site --exclude 'zenodo\.org' _site
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@c2750eb7eb937599ac859517e7dd23a29f1b3ed7 #v2
        with:
          directory: "_site"
          arguments: |
            --ignore-files "/.+\/_posts\/README.md"
            --checks "Images,Scripts"
