name: Link check (weekly)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "10 02 * * 6"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Fetch main
        run: |
          git fetch origin main --depth 1
          git branch

      - name: Setup Ruby
        uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c #v1.290.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 #v2.8.0
        with:
          args: >
            --verbose
            --no-progress
            --root-dir _site
            --exclude 'zenodo\.org'
            _site
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
