# Used to lint GitHub actions. https://github.com/rhysd/actionlint
name: Actionlint

on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actionlint:
    name: Action lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check workflow files
        uses: rhysd/actionlint@35082e035dc23c2dea5e58bbde3cfe1523204498 # v1.7.7
        with:
          args: -color -ignore SC2129
