# Used to lint GitHub actions. https://github.com/rhysd/actionlint
name: Actionlint

on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actionlint:
    name: Action lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check workflow files
        uses: rhysd/actionlint@393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11
        with:
          args: -color -ignore SC2129
